### ISSUE TITLE
Don't collide with panel placed on the side

### ISSUE THREAD

**Issue by xvello** [davidosomething/yanjing#1]
Hello, and thanks a lot for your work!

My main plasma panel is on the left side of the screen, like on this screenshot:
![Example screenshot with plasma panel on the left](https://userbase.kde.org/images.userbase/4/4a/Multipanel.png)

When using the standard kwin `Meta+Left` shortcut to tile windows to the left, they are correctly placed alongside the panel, and sized to 50% of the available space (total width - panel width). When using `Yanjing yMax + LEFT`, the window is placed *under the panel*, at y=0 in absolute coordinates.

The behaviour I'd expect is for the position/width computation to be bounded by the area of a maximized window, instead of the full screen. It looks like [kwin's native placement logic](https://github.com/KDE/kwin/blob/93e0265e4e4501cb5459423892e770029e43edfd/src/placement.cpp#L825) uses the `MaximizeArea` client area. As a total kwin scripting noob, I have no idea how to use this in JS though.

**Comment by davidosomething** [comment]
Updated, should be fixed if you install v4.0.0 from store.kde.org

**Comment by xvello** [comment]
Thanks a lot David, it works great!

I have another minor bug and a feature request I'll open issues for, but I'm very grateful for your project :bow:
