### ISSUE TITLE
Restore window shadow when flushing a maximized window

### ISSUE THREAD

**Issue by xvello** [davidosomething/yanjing#2]
When a window is maximized (for example, kwin starts firefox maximized by default), the `Yanjing yMax + LEFT` (or right) action does flush it correctly to the side, but does not reset its maximized status, leading to the window not having a shadow. Note that this does not happen if the window is not maximized prior to flushing.

While this should be automatic, it looks like kwin does not update the maximized status when the script resizes a window, and this needs to be set explicitly. I patched the `Yanjing.yMax` function to call `client.setMaximize(true, false);` before setting its geometry, and it seems to do the trick: the flushed window now has a shadow regardless of its previous state.

I did not directly submit a PR because you might want to investigate a "cleaner" solution to this, also working for the non yMax actions. Maybe you could wrap the `client.geometry` access into a function that compares the target size to the work area, and set the maximize status accordingly?

**Comment by davidosomething** [comment]
setMaximize was the way to go, but I made it restore the maximized size after removing the maximized state

I don't want windows resized by this script to EVER be considered maximized (not even vertically maximized in yMax), so it will always `setMaximized(false, false)`
I may present it as an option if I can get the config ui working from #3 

released in v4.1.0 in the store now

**Comment by xvello** [comment]
Works great with 4.1.1, thanks again :bow:
